version: 0.2

phases:
  pre_build:
    commands:
      - echo Iniciando login en ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 997141224904.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Construyendo imagen...
      - docker build -t imagesalary .
      - docker tag imagesalary:latest 997141224904.dkr.ecr.us-east-1.amazonaws.com/imagesalary:latest

  post_build:
    commands:
      - echo Subiendo imagen a ECR...
      - docker push 997141224904.dkr.ecr.us-east-1.amazonaws.com/imagesalary:latest
      - echo Actualizando Lambda...
      - aws lambda update-function-code --function-name PredictionSalary --image-uri 997141224904.dkr.ecr.us-east-1.amazonaws.com/imagesalary:latest --region us-east-1
